/*
    BLOG 
*/
// REDUCERS
export const RECEIVE_BLOGS_REDUCER = "RECEIVE_BLOGS_REDUCER"
export const POST_BLOG_REDUCER = "POST_BLOG_REDUCER"

// BLOG ACTION  TYPES
export const FETCH_BLOGS_TYPE = "FETCH_BLOGS_TYPE"
export const POST_BLOG_TYPE = "POST_BLOG_TYPE"

/*
    USER    
*/
// REDUCERS
export const LOGIN_USER_REDUCER = "LOGIN_USER_REDUCER"

// USER ACTION TYPES
export const LOGIN_USER_TYPE = "LOGIN_USER_TYPE"

/*
    COMMENT    
*/
// REDUCERS
export const RECEIVE_COMMENTBYID_REDUCER = "RECEIVE_COMMENTBYID_REDUCER"
export const RECEIVE_ALLCOMMENTS_REDUCER = "RECEIVE_ALLCOMMENTS_REDUCER"

// COMMENT ACTION TYPES
export const FETCH_COMMENTBYID_TYPE = "CLICK_COMMENTBYID_TYPE"
export const FETCH_ALLCOMMENTS_TYPE = "FETCH_ALLCOMMENTS_TYPE"
